hydra:
  searchpath:
    - file://scripts/dapo/config
    - file://verl/trainer/config
    - file://verl/verl/trainer/config
    - pkg://verl.verl.trainer.config

defaults:
  - dapo_trainer
  - _self_

data:
  train_files: /root/autodl-tmp/rl_data/mix_1000/mix_medium_train.parquet
  val_files: /root/autodl-tmp/rl_data/mix_1000/mix_medium_test.parquet
  prompt_key: prompt
  truncation: error
  max_prompt_length: 4096
  max_response_length: 8192 # 最大生成长度，8192+2048 = 10240
  filter_overlong_prompts: true
  # gen_batch_size: 4  # 关闭dapo的dynamic sampling后，实际起作用的是这个==train_batch_size
  train_batch_size: 8
  shuffle: false
  seed: 42
  apply_chat_template_kwargs:
    enable_thinking: true # 设置开启think

algorithm:
  adv_estimator: grpo
  norm_adv_by_std_in_grpo: true
  use_kl_in_reward: false
  kl_ctrl:
    kl_coef: 0.0
  filter_groups:
    enable: true
    max_num_gen_batches: 20
    metric: acc  # 参考 https://verl.readthedocs.io/en/latest/algo/dapo.html

# lora_adapter_path: 加载lora 权重
actor_rollout_ref:
  model:
    path: ${oc.env:MODEL_PATH,Qwen/Qwen3.5-9B}
    lora_rank: 64
    lora_alpha: 128
    target_modules: all-linear
    lora_adapter_path: /root/lg/QwenTraining/outputs/verl/DAPO_AutoDL/DAPO-Qwen3.5-9B_04-21_1448/global_step_150/actor/lora_adapter
    # lora_adapter_path: /data/wuli_error/WRX/QwenTraining/output/v52-20260404-111420/checkpoint-1
    use_remove_padding: true
    enable_gradient_checkpointing: true
    lora:
      merge: false
      freeze_vision_model: true
    override_config:
      dtype: bfloat16
      attn_implementation: flash_attention_2 # eager  / flash_attention_2

  actor:
    strategy: fsdp2
    use_kl_loss: true
    kl_loss_coef: 0.01
    clip_ratio_low: 0.2
    clip_ratio_high: 0.25
    entropy_coeff: 0
    grad_clip: 1.0
    loss_agg_mode: token-mean
    kl_loss_type: low_var_kl
    # use_torch_compile: false
    # ulysses_sequence_parallel_size: 1
    entropy_from_logits_with_chunking: true
    entropy_checkpointing: true
    optim:
      lr: 1e-6
      lr_scheduler_type: cosine
      min_lr_ratio: 0.1
      lr_warmup_steps_ratio: 0.03 # https://verl.readthedocs.io/en/latest/examples/config.html
    fsdp_config:
      param_offload: false
      optimizer_offload: false
      offload_policy: false
      reshard_after_forward: false
      fsdp_size: -1
      model_dtype: bfloat16
    checkpoint:
      save_contents: [] # 节省空间
    ppo_mini_batch_size: 2
    ppo_micro_batch_size_per_gpu: 1 # force 1 to not fault
    # use_dynamic_bsz: false # 开启动态调整batch size以适应显存见https://woniu9524.github.io/verl-doc/perf/perf_tuning.html
    # ppo_max_token_len_per_gpu: 8192

  # 当use_kl_loss为false以及 use_kl_in_reward=false时，不开启
  ref:
    model:
      override_config:
        attn_implementation: flash_attention_2
    # use_torch_compile: false
    # ulysses_sequence_parallel_size: 1
    entropy_from_logits_with_chunking: true
    fsdp_config:
      param_offload: false
      offload_policy: false
      reshard_after_forward: false
      model_dtype: bfloat16
    log_prob_micro_batch_size_per_gpu: ${actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu}
    # log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    # log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}

  rollout:
    # trace: # 添加查看val data的回答
    #   backend: None
    #   token2text: true  # 能够查看生成的text
    #   max_samples_per_step_per_worker: 3
    name: vllm
    enforce_eager: false  # 切换eager和flash-attn
    load_format: safetensors
    layered_summon: true # https://verl.readthedocs.io/en/latest/advance/ppo_lora.html
    free_cache_engine: true
    enable_chunked_prefill: true
    enable_prefix_caching: true
    # checkpoint_engine:
    #   update_weights_bucket_megabytes: 6144
    agent:
      num_workers: 1
    n: 8 # Group中的数量
    log_prob_micro_batch_size_per_gpu: ${actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu}
    # log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    # log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    gpu_memory_utilization: 0.8
    tensor_model_parallel_size: 1 # override
    max_num_seqs: 16  # 并行序列数，限制在一定范围内以避免显存不足
    # max_num_batched_tokens: 10240 # 单词推理最大长度
    max_model_len: 16384 # prompt+response最大长度，超过这个长度会被丢弃
    temperature: 1.0
    top_p: 0.95
    top_k: -1
    val_kwargs:
      temperature: 0.2
      top_p: 0.95
      top_k: -1
      do_sample: true
      n: 1

reward:
  reward_manager:
    name: dapo
  num_workers: 1
  reward_kwargs:
    overlong_buffer_cfg:
      enable: false
      len: 0
      penalty_factor: 0.0
      log: false
  custom_reward_function:
    path: scripts/plugins/verl_codegen1_raw_reward.py
    name: compute_score
    reward_kwargs:
      timeout_sec: 4
      memory_limit_mb: 1024

trainer:
  logger: ['console', 'wandb']
  # logger: ['console']
  project_name: DAPO_AutoDL
  experiment_name: DAPO-Qwen3.5-9B_${oc.env:EXP_TIME_SUFFIX}
  n_gpus_per_node: 1 # override
  nnodes: 1
  # balance_batch: false
  val_before_train: false
  save_dataloader_state: false # 关闭保存 data.pt
  max_actor_ckpt_to_keep: 3
  test_freq: 10
  save_freq: 10
  total_epochs: 1
  # total_training_steps: 20
  default_local_dir: ${oc.env:OUTPUT_DIR,./outputs/verl/${trainer.project_name}/${trainer.experiment_name}}
